task:
  - table-classification
  - qsar-classification
framework:
  - xgboost
  - sklearn
  - catboost

implementations:
  xgboost:
    accuracy:
      _target_: innofw.core.metrics.custom_metrics.metrics.Accuracy
    f_one:
      _target_: sklearn.metrics.f1_score
      average: macro

  sklearn:
    accuracy:
      _target_: sklearn.metrics.accuracy_score
    f_one:
      _target_: sklearn.metrics.f1_score
      average: macro
  
  catboost:
    accuracy:
      _target_: sklearn.metrics.accuracy_score
    f_one:
      _target_: sklearn.metrics.f1_score
      average: macro