task:
  - text-classification

name: noname
description: "Набор данных для классификации патологии легких по тексту"

markup_info: Набор данных содержит описание легких
date_time: 13.09.2023

_target_: innofw.core.datamodules.pandas_datamodules.lung_description_decision_datamodule.LungDescriptionDecisionPandasDataModule
target_col: decision

train:
#  source: https://api.blackhole.ai.innopolis.university/public-datasets/mnist/train.zip
#  target: ./data/mnist/train

  target: ./data/ainur/infer/labels.csv
  source: ./data/ainur/infer/labels.csv
test:
#  source: https://api.blackhole.ai.innopolis.university/public-datasets/mnist/test.zip
  target: ./data/ainur/infer/labels.csv
  source: ./data/ainur/infer/labels.csv
infer:
#  source: https://api.blackhole.ai.innopolis.university/public-datasets/mnist/infer.zip
  target: ./data/ainur/infer/labels.csv
  source: ./data/ainur/infer/labels.csv


