task:
  - table-regression

name: polymers
description: polymers properties

markup_info: Информация о разметке
date_time: 21.07.2022

_target_: innofw.core.datamodules.pandas_datamodules.PandasDataModule


train:
 source: ./data/polymers/train/train.csv
test:
 source: ./data/polymers/test/test.csv

val_size: 0.2
target_col: 
  - "Модуль упругости при изгибе_МПа"
  - "Xs_ISO 16152_%"
  - "Модуль упругости при растяжении_МПа"
  - "Относительное удлинение при пределе текучести_%"
  - "Относительное удлинение при разрыве_%"
  - "Предел текучести при растяжении_МПа"
  - "Прочность при разрыве_МПа"
  - "Твердость по Шору_D/1"
  - "Твердость по Шору_D/15"
  - "Температура изгиба под нагрузкой 0,45МПа_C"
  - "Температура размягчения по Вика, С_10Н"
  - "Температура размягчения по Вика, С_50Н"
  - "Ударная вязкость по Изоду с/н, 23 C_ISO 180_кДж/м2"
  - "Ударная вязкость по Изоду с/н, 23 C_Дж/м"
