task:
  - image-detection

name: detection_lep
description: Набор данных содержит видео облетов c дронов над территорией линии электропередач

markup_info: Набор данных содержит разметку bounding box, под формат детекции столбов ЛЭП.
date_time: 18.07.2022

_target_: innofw.core.integrations.ultralytics.datamodule.UltralyticsDataModuleAdapter

train:
  source: /mnt/nvmestorage/qb/repos/exp/2100723/innofw/data/proper_lep/images/train
  # source: https://api.blackhole.ai.innopolis.university/public-datasets/testing/lep/train.zip
  # target: ./data/lep/train
test:
  source: /mnt/nvmestorage/qb/repos/exp/2100723/innofw/data/proper_lep/images/test
  # source: https://api.blackhole.ai.innopolis.university/public-datasets/testing/lep/test.zip
  # target: ./data/lep/test
infer:
  source: /mnt/nvmestorage/qb/repos/exp/2100723/innofw/data/proper_lep/images/infer
  # source: https://api.blackhole.ai.innopolis.university/public-datasets/testing/lep/test.zip
  # target: ./data/lep/infer


num_workers: 8

val_size: 0.2
channels_num: 3
image_size: 600
num_classes: 4
names:
  - lep_1
  - lep_2
  - lep_3
  - lep_4
