name: notlinear_regression
description: linear regression model

_target_: sklearn.pipeline.Pipeline
steps:
  - - "vectorizer"
    - _target_: sklearn.feature_extraction.text.TfidfVectorizer
      min_df: 10
  - - "classifier"
    - _target_: sklearn.linear_model.LogisticRegression
      multi_class: 'multinomial'
